[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "matrix_computations_helper"
version = "1.0"

[tool.setuptools]
packages = ["matrix_computations_helper"]